---
title: "bayesian regression"
output: html_document
---



```{r}
# importing libraries
library(ggplot2)
library(MCMCpack)

```


```{r}
# loading sp500 stock list
sp500_stocks <- read.csv("sp500_stocks.csv")
head(sp500_stocks)

```

```{r}
# loading final data
stock_data <- read.csv("finaldata.csv")
head(stock_data)

```



```{r}
# getting stocks columns in finaldata
column_names <- grep("_(RETURN|STDDEV|ROLL_AVG)$", colnames(stock_data), value = TRUE)

# extracting ticker names from those columns
extracted_tickers <- unique(sub("_(RETURN|STDDEV|ROLL_AVG)$", "", column_names))

# filtering sp500_stocks using the extracted tickers
sp500_stocks <- sp500_stocks[sp500_stocks$Ticker %in% extracted_tickers, ]
head(sp500_stocks)

```


```{r}

similar_stocks <- function(stock) {
  
  # getting sector in which the stock is
  sector <- sp500_stocks$Sector[sp500_stocks$Ticker == stock]
  
  # getting peers in the same sector
  peers <- sp500_stocks$Ticker[sp500_stocks$Sector == sector]
  
  # excluding the input stock
  peers <- peers[peers != stock]
  
  return(peers)
  
}

input_stock <- similar_stocks("AMZN")
input_stock

```



#### Predicting Standard deviation using Gamma Distribution with Gamma Prior (known alpha)

```{r}

# Prior 
gamma_prior <- function(x, alpha, beta) {
  return(dgamma(x, shape=alpha, scale=beta))
}

# Posterior 
gamma_posterior <- function(x, alpha_likelihood, alpha_prior, beta_prior, sim_data) {
  n <- length(sim_data)
  alpha_star <- n * alpha_likelihood + alpha_prior
  beta_star <- beta_prior + sum(1/sim_data)
  
  return(dgamma(x, shape = alpha_star, scale = 1/beta_star))
}
```

```{r}
# Define the macro columns that are always needed
macro_cols <- c("Inflation.Rate", "RF")

# For each similar stock, generate the expected column names
stock_cols <- as.vector(outer(input_stock,
                              c("RETURN", "STDEV", "ROLL_AVG"),
                              FUN = function(x, y) paste(x, y, sep = "_")))

# Subset the data with the desired macro columns and stock-specific columns
filtered_data <- stock_data[, c(macro_cols, stock_cols)]

# Display the first few rows of the filtered data
head(filtered_data)


```

```{r}
# getting stddev columns in finaldata
stddev_cols <- grep("_STDEV$", colnames(filtered_data), value = TRUE)

# extracting stddev df
stddev_df <- filtered_data[, stddev_cols]

# getting variances of all stocks in sector
variance_df <- stddev_df^2
head(variance_df)

# flattening variance
flatten_variance <- unlist(variance_df)
flatten_variance

```

```{r}
stock_variance <- function(stock) {
  
  # create column name
  target_col <- paste0(stock, "_STDEV")
  
  sim_data <- stock_data[[target_col]]^2
  hist(sim_data, freq = F)
  
  return(sim_data)
  
}

user_stock <- stock_variance("AMZN")
user_stock

```

```{r}
# defining alpha likelihood
alpha_likelihood <- 2

# defining priors
alpha_prior <- 1
beta_prior <- mean(flatten_variance) / alpha_prior

# defining prior mean
prior_mean <- alpha_prior*beta_prior

#x_vals <- seq(0, max(sim_data), length.out = 500)
#x_vals <- seq(0, max(stdev$AAPL^2), length.out = 500)
x_vals <- seq(0, quantile(user_stock, 0.99), length.out = 500)

prior_dist <- gamma_prior(x_vals, alpha_prior, beta_prior)
post_dist <- gamma_posterior(x_vals, alpha_likelihood, alpha_prior, beta_prior, user_stock)


ggplot() +
  geom_line(aes(x = x_vals, y = prior_dist, color = "Prior"), size = 1.2) +
  geom_line(aes(x = x_vals, y = post_dist, color = "Posterior"), size = 1.2) +
  geom_vline(aes(xintercept = prior_mean, color = "Prior Mean"), linetype = "dashed", size = 1) + 
  scale_color_manual(values = c("Prior" = "red", 
                                "Posterior" = "purple", 
                                "Prior Mean" = "red")) +
  labs(x = expression(theta), Dy = "Density", title = "Gamma Prior vs. Posterior Distribution (AAPL)") +
  theme_minimal() +
  theme(legend.title = element_blank())

```


IMperical bayes 
to choose parameters 

training data to ifnorm alpha 0 and beta 0 
and then fit the model on posterior 





### Supervised ML

```{r}
# msft <- read.csv('MSFT.csv')
# head(msft)
# 
# 
# y <- msft$MSFT_STDEV
# 
# X_data <- subset(msft, select = -c(MSFT_STDEV, Next_MSFT_RETURN))
# X_numeric <- X_raw[sapply(X_raw, is.numeric)]
# 
# X_scaled <- scale(X_numeric)
# X <- cbind(X_scaled, bias = 1)
```


```{r}
# n <- length(data)
# alpha_star <- n * alpha_likelihood + alpha_prior
# beta_star <- beta_prior + sum(data)


```

```{r}
stdev_df <- read.csv('monthly_stdev.csv')
colnames(stdev_df)
```
```{r}
# testing tech stocks since thats already in the portfolio

# get tech stocks
# ideally this should pull based on sector column
tech_df <- stdev_df[, c("AVGO", "CRM", "CSCO", "GDDY", "HUBS", "MSFT",
                        "NOW", "QCOM", "TSM")]

head(tech_df)

# getting variances of all stocks in sector
variance_df <- tech_df^2
head(variance_df)

# flattening variance
flatten_variance <- unlist(variance_df)
#flatten_variance

```


```{r}
# defining alpha likelihood
alpha_likelihood <- 2

# defining priors
alpha_prior <- 1
beta_prior <- mean(flatten_variance) / alpha_prior

# defining prior mean
prior_mean <- alpha_prior*beta_prior

#x_vals <- seq(0, max(sim_data), length.out = 500)
#x_vals <- seq(0, max(stdev$AAPL^2), length.out = 500)
x_vals <- seq(0, quantile(sim_data, 0.99), length.out = 500)

prior_dist <- gamma_prior(x_vals, alpha_prior, beta_prior)
post_dist <- gamma_posterior(x_vals, alpha_likelihood, alpha_prior, beta_prior, sim_data)


ggplot() +
  geom_line(aes(x = x_vals, y = prior_dist, color = "Prior"), size = 1.2) +
  geom_line(aes(x = x_vals, y = post_dist, color = "Posterior"), size = 1.2) +
  geom_vline(aes(xintercept = prior_mean, color = "Prior Mean"), linetype = "dashed", size = 1) + 
  scale_color_manual(values = c("Prior" = "red", 
                                "Posterior" = "purple", 
                                "Prior Mean" = "red")) +
  labs(x = expression(theta), Dy = "Density", title = "Gamma Prior vs. Posterior Distribution (AAPL)") +
  theme_minimal() +
  theme(legend.title = element_blank())

```

```{r}
# assume we are not very certain (confident) about what the true risk value is.
# so prior is flatter and spread out - open to wide range of variance value
# this is what "greater uncertainty" means


# for bayesian - you need to exclude target value from the stack?
# prior is weak but informed because youre not confident of the true value
# but it reflects informed data rather than random


# after AAPL data is included, you see posterior is taller and narrower
# contrast between prior and posterior shows how evidence refines beliefs

```