---
title: "project_bayesian"
output: html_document
date: "2025-04-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

# importing libraries
library(ggplot2)
library(MCMCpack)
library(shiny)
library(bslib)

```

```{r}
# loading sp500 stock list (results from python)
sp500_stocks <- read.csv("filtered_sp500_stocks.csv")
colnames(sp500_stocks)[1] <- 'Ticker'
#sp500_stocks

```

```{r}
# loading final data (from python)
stock_data <- read.csv("result.csv")
#head(stock_data)

```

```{r}
# ensuring all stocks in sp500 list and stock data match
# getting stocks columns in finaldata
column_names <- grep("_(RETURN|STDDEV|ROLL_AVG)$", colnames(stock_data), value = TRUE)

# extracting ticker names from those columns
extracted_tickers <- unique(sub("_(RETURN|STDDEV|ROLL_AVG)$", "", column_names))

# filtering sp500_stocks using the extracted tickers
sp500_stocks <- sp500_stocks[sp500_stocks$Ticker %in% extracted_tickers, ]
#head(sp500_stocks)

```

```{r}

similar_stocks <- function(stock, sim_range=TRUE) {
  
  # getting sector in which the stock is
  sector <- sp500_stocks$Sector[sp500_stocks$Ticker == stock]
  
  
  if (sim_range) {
    
    # getting similar priced stocks
    price <- sp500_stocks$Last_Price[sp500_stocks$Ticker == stock]
    range = .25
    price_lower_bound <- price * (1 - range)
    price_upper_bound <- price * (1 + range)
  
    cat("Price of", stock, ":", price, price_lower_bound, price_upper_bound, "\n")
    
    # getting peers in the same sector
    peers <- sp500_stocks$Ticker[sp500_stocks$Sector == sector]
    
    # excluding the input stock
    peers <- peers[peers != stock]
    
    
    related_sector <- sp500_stocks[sp500_stocks$Ticker %in% peers &
                                   sp500_stocks$Last_Price >= price_lower_bound &
                                   sp500_stocks$Last_Price <= price_upper_bound, ]
  
    return(related_sector$Ticker)
    
  }
  else {
    
    # getting peers in the same sector
    peers <- sp500_stocks$Ticker[sp500_stocks$Sector == sector]
    
    # excluding the input stock
    peers <- peers[peers != stock]
    
    return(peers)
    
  }
  
}

input_stock <- similar_stocks("NVDA")
#input_stock

```

```{r}

# Prior 
gamma_prior <- function(x, alpha, beta) {
  return(dgamma(x, shape=alpha, scale=beta))
}

# Posterior 
gamma_posterior <- function(x, alpha_likelihood, alpha_prior, beta_prior, sim_data) {
  n <- length(sim_data)
  alpha_star <- n * alpha_likelihood + alpha_prior
  beta_star <- beta_prior + sum(1/sim_data)
  
  return(dgamma(x, shape = alpha_star, scale = 1/beta_star))
}
```

```{r}

get_filtered_df <- function(sim_stock) {
  
  # getting macro columns
  macro_cols <- c("Inflation.Rate", "RF")

  # getting return, stddev, roll avg for similar stocks
  stock_cols <- as.vector(outer(sim_stock,
                              c("RETURN", "STDEV", "ROLL_AVG"),
                              FUN = function(x, y) paste(x, y, sep = "_")))

  # getting required columns
  filtered_data <- stock_data[, c(macro_cols, stock_cols)]
  
  return(filtered_data)
  
}


filtered_data <- get_filtered_df(input_stock)
#filtered_data
```

```{r}

get_variance <- function(filtered_df) {
  
  # getting stddev columns in finaldata
  stddev_cols <- grep("_STDEV$", colnames(filtered_df), value = TRUE)

  # extracting stddev df
  stddev_df <- filtered_df[, stddev_cols]

  # getting variances of all stocks in sector
  variance_df <- stddev_df^2
  head(variance_df)

  # flattening variance
  flatten_variance <- unlist(variance_df)  
  
  return(flatten_variance)
  
}

flatten_variance <- get_variance(filtered_data)
#flatten_variance

```

```{r}
stock_variance <- function(stock) {
  
  # create column name
  target_col <- paste0(stock, "_STDEV")
  
  sim_data <- stock_data[[target_col]]^2

  return(sim_data)
  
}

user_stock <- stock_variance("NVDA")
#user_stock

```

```{r}

get_plot <- function(alpha_likelihoodi, alpha_priori, sim_var, stock_var) {
  # defining alpha likelihood
  alpha_likelihood <- alpha_likelihoodi

  # defining priors
  alpha_prior <- alpha_priori
  beta_prior <- mean(sim_var) / alpha_prior

  # defining prior mean
  prior_mean <- alpha_prior*beta_prior
  
  # calculating posterior mean
  n <- length(stock_var)
  alpha_star <- n * alpha_likelihood + alpha_prior
  beta_star <- beta_prior + sum(1/stock_var)
  
  posterior_mean <- alpha_star * (1/beta_star)
  
  # finding change in mean
  pct_change <- (posterior_mean - prior_mean) / prior_mean*100
  
  # calculating mae
  mae <- mean(abs(posterior_mean - prior_mean)^2)
  
  #x_vals <- seq(0, max(sim_data), length.out = 500)
  #x_vals <- seq(0, max(stdev$AAPL^2), length.out = 500)
  x_vals <- seq(0, quantile(stock_var, 0.99), length.out = 500)
  
  prior_dist <- gamma_prior(x_vals, alpha_prior, beta_prior)
  post_dist <- gamma_posterior(x_vals, alpha_likelihood, alpha_prior, beta_prior, stock_var)
  
  
  result <- ggplot() +
      geom_line(aes(x = x_vals, y = prior_dist, color = "Prior"), size = 1.2) +
      geom_line(aes(x = x_vals, y = post_dist, color = "Posterior"), size = 1.2) +
      geom_vline(aes(xintercept = prior_mean, color = "Prior Mean"), linetype = "dashed", size = 0.5) +
      geom_vline(aes(xintercept = posterior_mean, color = "Posterior Mean"), linetype = "dashed", size = 0.5) +
      scale_color_manual(values = c("Prior" = "red", 
                                    "Posterior" = "purple", 
                                    "Prior Mean" = "red",
                                    "Posterior Mean" = "purple")) +
      labs(x = expression(theta), Dy = "Density", title = "Gamma Prior vs. Posterior Distribution") +
      theme_minimal() +
      theme(legend.title = element_blank())
  
  return(list(plot = result, priormean = prior_mean, posteriormean = posterior_mean, 
              pctchange = pct_change, mae = mae)) 
}
  

std_plot <- get_plot(2, 1, flatten_variance, user_stock)
std_plot
```

```{r}
### ANALYSIS

sector_analysis <- function(sector, alpha_likelihoodi, alpha_priori) {
  
  # getting stocks in each sector in which the stock is
  stocks <- sp500_stocks$Ticker[sp500_stocks$Sector == sector]
  cat(stocks)
  
  filtered_df <- get_filtered_df(stocks)
  
  sector_var <- get_variance(filtered_df)
  
  # defining alpha likelihood
  alpha_likelihood <- alpha_likelihoodi

  # defining priors
  alpha_prior <- alpha_priori
  beta_prior <- mean(sector_var) / alpha_prior

  # defining prior mean
  prior_mean <- alpha_prior*beta_prior
  
  # calculating posterior mean
  n <- length(sector_var)
  alpha_star <- n * alpha_likelihood + alpha_prior
  beta_star <- beta_prior + sum(1/sector_var)
  
  posterior_mean <- alpha_star * (1/beta_star)
  
  # finding change in mean
  pct_change <- (posterior_mean - prior_mean) / prior_mean * 100
  
  # calculating mae
  mae <- mean(abs(posterior_mean - prior_mean)^2)
  
  #x_vals <- seq(0, max(sim_data), length.out = 500)
  #x_vals <- seq(0, max(stdev$AAPL^2), length.out = 500)
  x_vals <- seq(0, quantile(sector_var, 0.95), length.out = 500)
  
  prior_dist <- gamma_prior(x_vals, alpha_prior, beta_prior)
  post_dist <- gamma_posterior(x_vals, alpha_likelihood, alpha_prior, beta_prior, sector_var)
  
  
  result <- ggplot() +
      geom_line(aes(x = x_vals, y = prior_dist, color = "Prior"), size = 1.2) +
      geom_line(aes(x = x_vals, y = post_dist, color = "Posterior"), size = 1.2) +
      geom_vline(aes(xintercept = prior_mean, color = "Prior Mean"), linetype = "dashed", size = 0.5) +
      geom_vline(aes(xintercept = posterior_mean, color = "Posterior Mean"), linetype = "dashed", size = 0.5) +
      scale_color_manual(values = c("Prior" = "red", 
                                    "Posterior" = "purple", 
                                    "Prior Mean" = "red",
                                    "Posterior Mean" = "purple")) +
      labs(x = expression(theta), Dy = "Density", title = "Gamma Prior vs. Posterior Distribution") +
      theme_minimal() +
      theme(legend.title = element_blank())
  
  print(result)
  cat("Prior Mean:", prior_mean, "\n") 
  cat("Posterior Mean:", posterior_mean, "\n")
  cat("Percentage Change in Means:", pct_change, "% \n")
  cat("Mean Absolute Error (MAE):", mae, "\n")
  
  
}

```

```{r}
for (i in unique(sp500_stocks$Sector)) {
  
  cat("Sector Analysis ", i, "\n")
  results <- sector_analysis(i, 2, 1)
  
  print(results)
}

```




```{r}

# creating app

ui <- page_navbar(
  title = "Stock Volatility Calculator",
  
  nav_panel(title = "Project Description", 
  
  fluidPage(
    tags$h1("Stock Variance Prediction Using Bayesian Modeling"),
    
    tags$div(
     tags$h5(
       "This app serves as a financial tool for investors to make informed decisions by understanding
        the volatility of a stock compared to its peers. The volatility or variance of a stock is 
        calculated using an Inverse Gamma-Gamma Bayesian Model. For this model, we make an assumption that 
        the variance of the stock chosen behaves similarly to the mean variance similar stocks in the same sector. The 'Get Stocks with Similar Prices' Option further constrains it to other stocks with a comparable price and same sector, allowing for a more tailored prior belief and is useful for users who are knowledgeable and believe price similarity reflects comparable risk profiles."),
     tags$br(),
     tags$h3("Inverse Gamma-Gamma Model Explanation"),
     tags$h5("The Inverse Gamma distribution with a known alpha is a commonly used distribution to model
              uncertainty or variance of a normal distribution. It has two parameters - alpha & beta. The
              alpha determines the height of the distribution and the beta determines the spread. These 
              hyperparameters show the level of certainty or uncertainty in our prior beliefs. The gamma
              distribution is a conjugate prior and models the behavior of variance well since it models 
              positive continuous values."),
     tags$br(),
     tags$h3("Explanation of Terms"),
     tags$h5("Stock: The stock's ticker for which you want the variance."),
     tags$h5("Get Stocks with Similar Price: If you believe that the variance of a stock should be calculated
              using the mean variance of stocks that are not only within the same sector but also around the
              same price range, then please select this option."),
     tags$h5("Alpha Likelihood: A weight of how strongly you believe the observed data influences the
              variance of a stock. For this calculator, the observed data is based on S&P500 Stocks since
              2005."),
     tags$h5("Alpha Prior: A measure of how strong your trust is on your prior belief on the distribution of the variance before seeing any new data."),
      tags$h5("Beta Prior: The scale parameter of the prior, derived from the mean of similar stocks in the same sector, adjusting the spread of the prior distribution and certainty."),
     tags$h5("Posterior Mean Estimate: This is the estimated mean of the stock's volatility after considering
              the initial assumption and the observed data. A higher mean will indicate that there is more
              variance, while a lower mean will indicate that there is low volatility.")
    )
    
  )
  ),
  
  nav_panel(title = "Calculator",
  
  page_sidebar(
  title = "Your S&P 500 Stock Volatility",
  
  sidebar = sidebar(
    # Select stock ticker
    selectInput(
      inputId = "stock_ticker",
      label = "Select Stock Ticker",
      choices = sort(sp500_stocks$Ticker)
    ),
    # Select Price Range
    checkboxInput(
      inputId = "price_range",
      label = "Get Stocks with Similar Price",
      value = TRUE
    ),
    
    # Select Alpha Likelihood
    numericInput(
      inputId = "alpha_likelihood",
      label = "Select Alpha Likelihood",
      value = 2,
      min = 0.1,
      step = 0.1
    ),
    # Select Alpha Prior
    numericInput(
      inputId = "alpha_prior",
      label = "Select Alpha Prior",
      value = 1,
      min = 0.1,
      step = 0.1
    ),
  ),
  # Output: Show scatterplot
  card(plotOutput(outputId = "distPlot")),
  card(tableOutput(outputId = "analysis")),
  
)
),

  nav_spacer(),
  nav_menu(
    title = "Links",
    align = "right",
    nav_item(tags$a("GitHub", href = "https://github.com/rishitashroff/riskreturncalculator")),
    nav_item(tags$a("Project Report", href = "https://docs.google.com/document/d/1-CrjMQnKnEyCtS8y46VeBVVLz2ILXbv-j_w-0QGlTTc/edit?usp=sharing")),
    nav_item(tags$a("Virtual Poster", href = "https://northeastern-my.sharepoint.com/:p:/r/personal/shroff_ri_northeastern_edu/Documents/poster%201.pptx?d=w1de8465d54e6483a863afd655bd72525&csf=1&web=1&e=GecrhF"))
  ),

  theme = bs_theme(preset = "yeti")

)

# Define server

server <- function(input, output, session) {
  
  output$analysis <- renderTable({
    
    # getting user stock input
    stock_input <- input$stock_ticker
    user_price_choice <- input$price_range
    alpha_likelihood <- input$alpha_likelihood
    alpha_prior <- input$alpha_prior
    
    # getting similar stocks
    sim_stocks <- similar_stocks(stock_input, user_price_choice)
    
    # getting filtered df
    filtered_data <- get_filtered_df(sim_stocks)
    
    # getting variances of similar stocks
    flatten_variance <- get_variance(filtered_data)
    
    # getting stock variance
    target_variance <- stock_variance(stock_input)
    
    # getting analysis from plot function
    std_plot <- get_plot(alpha_likelihood, alpha_prior, flatten_variance, target_variance)
    
    # creating a df of analysis so it can be outputed in table format
    analysis_table <- data.frame("Data Label" = c("Prior Mean Estimate", "Posterior Mean Estimate",
                                   "Percentage Change in Estimates (%)", "Mean Absolute Error"),
                                 "Values" = c(std_plot$priormean, std_plot$posteriormean,
                                              std_plot$pctchange, std_plot$mae))
  
  },
  
  striped = TRUE, spacing = "l", align = "l", digits = 15, width = "90%"
  
  )
  
  
  output$distPlot <- renderPlot({
    
    # getting user stock input
    stock_input <- input$stock_ticker
    user_price_choice <- input$price_range
    alpha_likelihood <- input$alpha_likelihood
    alpha_prior <- input$alpha_prior
    
    # getting similar stocks
    sim_stocks <- similar_stocks(stock_input, user_price_choice)
    
    # getting filtered df
    filtered_data <- get_filtered_df(sim_stocks)
    
    # getting variances of similar stocks
    flatten_variance <- get_variance(filtered_data)
    
    # getting stock variance
    target_variance <- stock_variance(stock_input)
    
    # getting plot
    std_plot <- get_plot(alpha_likelihood, alpha_prior, flatten_variance, target_variance)
    
    std_plot$plot
    
  })
}

# Create a Shiny app object

shinyApp(ui = ui, server = server)


```